# Generated by Django 6.0.1 on 2026-01-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_community_user_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='short_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
